server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Adewole171200
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true